# Site settings
title: "Lee Sharma"
email: lee@leesharma.com
description: "A personal homepage for Lee Sharma."
baseurl: ""
url: "http://leesharma.com/"
title_description: "Hello, my name is Lee Sharma. I am a developer, student, runner, reader, traveller, and generally awesome person."
title_image: "https://s.gravatar.com/avatar/afb4406ce3938c95df8414b178ef2b85?s=150"
google_analytics: "UA-20365477-4"
disqus_account: lee_sharma
github_repository: https://github.com/leesharma
post_limit: 5

# Social usernames/URLs
#twitter_username: theleesharma
# google_scholar_link:
github_username:  leesharma
# linkedin_link:
# google_plus_link:
# stackoverflow_link: http://stackoverflow.com/users/688244/lee
codepen_link: http://codepen.io/leesharma/

# Footer
footer: #"This site has a footer. &hearts;"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
